import Sidebar from '@/components/ui/sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <div className="flex dark"> */}
        <div className="w-1/4">
          <Sidebar />
        </div>
        {/* <div className="w-3/4 dark"> */}
          <main className={inter.className}>{children}</main>
        {/* </div> */}
      {/* </div> */}
    </html>
  )
}
