import Sidebar from '@/components/ui/sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/ui/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <div className="flex dark"> */}
      <Navbar/>
      <div className='flex'>
        <div className="w-[20vw]">
          <Sidebar />
        </div>

          <main className={inter.className} >
        <div 
        // className="ml-[20vw]"
        >
            {children}
        </div>
            </main>
            </div>
      {/* </div> */}
    </html>
  )
}
